language: rust
dist: trusty
os:
  - linux

rust:
  - nightly
cache: cargo
branches:
  only:
    - master

addons:
  postgres: '9.6'

before_script:
  - export DATABASE_URL=postgres://postgres@localhost
  - psql -U postgres -c "CREATE DATABASE test;"

script:
  - cargo build --verbose --features "clippy"
  - cargo test --verbose
