[package]
authors = ["Krishan Wyse <kwysek@gmail.com>"]
name = "hub"
version = "0.1.0"

[dependencies]
regex = "0.2.2"
serde = "1.0.10"
serde_derive = "1.0.10"
slog = "2.0.6"
slog-async = "2.0.1"
slog-term = "2.0.2"

[dependencies.config]
git = "https://github.com/mehcode/config-rs"
